In [5]:
f = open("Foodmart_2020_PD.csv", "r")
i= 0
for x in f:
    i+=1
    counter1 = x.count('=') 
    counter2 = x.count(',') 
    if counter1 != (counter2+1):
        print(i, ":", counter1-counter2-1)

In [113]:
#Csv para Dataframe
import csv
import pandas as pd

with open('Foodmart_2020_PD.csv', newline='') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=',')
    data = list(spamreader)

df = pd.DataFrame(data)

In [114]:
for x in range(1,14):

    df[x] = df[x].str.split("=", n = 1, expand = True)

In [43]:
import numpy as np

aux = df[1]
for x in range(2,14):
    
    aux = aux.append(df[x])

In [56]:
aux =  list(dict.fromkeys(aux))
aux.remove(None)

['Pasta',
 'Soup',
 'Cheese',
 'Fresh Vegetables',
 'Cleaners',
 'Dips',
 'Cookies',
 'Beer',
 'Nasal Sprays',
 'Rice',
 'Lightbulbs',
 'Bologna',
 'Spices',
 'Waffles',
 'Eggs',
 'Muffins',
 'Shampoo',
 'Milk',
 'Fresh Fruit',
 'Preserves',
 'Deli Meats',
 'Jelly',
 'Plastic Utensils',
 'Jam',
 'Tofu',
 'Popsicles',
 'Hot Dogs',
 'Cereal',
 'Batteries',
 'Personal Hygiene',
 'Chocolate Candy',
 'Cooking Oil',
 'Paper Wipes',
 'Peanut Butter',
 'Hard Candy',
 'Sour Cream',
 'Juice',
 'Ibuprofen',
 'Canned Vegetables',
 'Deodorizers',
 'Chips',
 'Pretzels',
 'Sliced Bread',
 'Nuts',
 'Dried Fruit',
 'Crackers',
 'Home Magazines',
 'Wine',
 'Deli Salads',
 'Pots and Pans',
 'Flavored Drinks',
 'Soda',
 'Pot Cleaners',
 'Ice Cream',
 'Donuts',
 'Frozen Chicken',
 'Candles',
 'Frozen Vegetables',
 'Popcorn',
 'French Fries',
 'Coffee',
 'Sunglasses',
 'Sponges',
 'Cottage Cheese',
 'Sauces',
 'Oysters',
 'Gum',
 'Anchovies',
 'Pizza',
 'Tools',
 'Dried Meat',
 'Maps',
 'Screwdrivers',
 'Mouthwash',
 'Fashion Magazines',
 'Tuna',
 'Fresh Chicken',
 'Conditioner',
 'Yogurt',
 'Aspirin',
 'Toothbrushes',
 'TV Dinner',
 'Paper Dishes',
 'Pancake Mix',
 'Sugar',
 'Shellfish',
 'Computer Magazines',
 'Hamburger',
 'Toilet Brushes',
 'Canned Fruit',
 'Cold Remedies',
 'Auto Magazines',
 'Clams',
 'Bagels',
 'Shrimp',
 'Sports Magazines',
 'Pot Scrubbers',
 'Fresh Fish',
 'Chocolate',
 'Pancakes',
 'Sardines',
 'Acetominifen']

In [63]:
df_enconded = pd.DataFrame(aux)

def custom():
    
    encoded_vals = []
    for index, row in df.iterrows():
        labels = {}
        uncommons = list(set(aux) - set(row))
        commons = list(set(aux).intersection(row))
        for uc in uncommons:
            labels[uc] = 0
        for com in commons:
            labels[com] = 1
        encoded_vals.append(labels)
    encoded_vals[0]
    ohe_df = pd.DataFrame(encoded_vals)
    
    return ohe_df
ohe_df = custom()

In [78]:
from mlxtend.frequent_patterns import apriori, association_rules

frequent_itemsets = apriori(ohe_df, min_support=0.05, use_colnames=True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

     support                         itemsets  length
0   0.054623                        (Waffles)       1
1   0.056320                   (Sliced Bread)       1
2   0.052395                           (Soda)       1
3   0.105422                        (Cookies)       1
4   0.284461               (Fresh Vegetables)       1
5   0.067176                           (Nuts)       1
6   0.068340              (Frozen Vegetables)       1
7   0.056277                     (Lightbulbs)       1
8   0.053617                     (Deli Meats)       1
9   0.078966                    (Paper Wipes)       1
10  0.066744                (Chocolate Candy)       1
11  0.064070                           (Eggs)       1
12  0.064746                          (Chips)       1
13  0.052783                      (Popsicles)       1
14  0.117845                         (Cheese)       1
15  0.054321                         (Cereal)       1
16  0.053689                          (Juice)       1
17  0.053962                      (Batteries)       1
18  0.066040                      (Preserves)       1
19  0.054868                           (Dips)       1
20  0.175286                    (Fresh Fruit)       1
21  0.054250                    (Cooking Oil)       1
22  0.052912                         (Coffee)       1
23  0.080677                           (Wine)       1
24  0.054048                          (Pizza)       1
25  0.078549              (Canned Vegetables)       1
26  0.117227                    (Dried Fruit)       1
27  0.066342                           (Milk)       1
28  0.055127                        (Muffins)       1
29  0.054623               (Personal Hygiene)       1
30  0.120059                           (Soup)       1
31  0.050971  (Fresh Fruit, Fresh Vegetables)       2

In [83]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.1)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Fresh Fruit),(Fresh Vegetables),0.175286,0.284461,0.050971,0.290788,1.022242,0.001109,1.008921
1,(Fresh Vegetables),(Fresh Fruit),0.284461,0.175286,0.050971,0.179185,1.022242,0.001109,1.004750

In [88]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Fresh Fruit),(Fresh Vegetables),0.175286,0.284461,0.050971,0.290788,1.022242,0.001109,1.008921
1,(Fresh Vegetables),(Fresh Fruit),0.284461,0.175286,0.050971,0.179185,1.022242,0.001109,1.004750

In [90]:
rules[(rules['confidence'] > 0.2) & (rules['lift'] > 1.0)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Fresh Fruit),(Fresh Vegetables),0.175286,0.284461,0.050971,0.290788,1.022242,0.001109,1.008921

In [104]:
from mlxtend.frequent_patterns import fpmax

fpmax(ohe_df, min_support=0.25, use_colnames=True)

    support            itemsets
0  0.284461  (Fresh Vegetables)

#### 2

In [131]:
#df[0] = df[0].str.split(r'=').str[1]

deluxe_df = df.loc[(df[0].isin(['8','12', '13', '17', '19', '21']))]
gourmet_df = df.loc[(df[0].isin(['4','6']))]
mid_size_df = df.loc[(df[0].isin(['9','18', '20', '23']))]
small_df = df.loc[(df[0].isin(['2','5', '14', '22']))]
supermarket_df = df.loc[(df[0].isin(['1', '3', '7', '10', '11', '15',' 16']))]
deluxe_gourmet_df = df.loc[(df[0].isin(['8','12', '13', '17', '19', '21', '4', '6']))]

#### Compute Frequent Itemsets - Deluxe e Gourmet juntos

In [133]:
aux = deluxe_gourmet_df[1]
for x in range(2,14):
    
    aux = aux.append(deluxe_df[x])

aux =  list(dict.fromkeys(aux))
aux.remove(None)

df_enconded_deluxe = pd.DataFrame(aux)

def custom():
    
    encoded_vals = []
    for index, row in df.iterrows():
        labels = {}
        uncommons = list(set(aux) - set(row))
        commons = list(set(aux).intersection(row))
        for uc in uncommons:
            labels[uc] = 0
        for com in commons:
            labels[com] = 1
        encoded_vals.append(labels)
    encoded_vals[0]
    ohe_df = pd.DataFrame(encoded_vals)
    
    return ohe_df
ohe_deluxe_gourmet = custom()

In [157]:
frequent_itemsets = apriori(ohe_deluxe_gourmet, min_support=0.01, use_colnames=True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

      support              itemsets  length
0    0.013731  (Computer Magazines)       1
1    0.027204        (Pot Cleaners)       1
2    0.054623             (Waffles)       1
3    0.056320        (Sliced Bread)       1
4    0.014249      (Home Magazines)       1
..        ...                   ...     ...
173  0.012337   (Fresh Fruit, Milk)       2
174  0.020805   (Fresh Fruit, Soup)       2
175  0.010137   (Dried Fruit, Wine)       2
176  0.011273          (Wine, Soup)       2
177  0.012193   (Dried Fruit, Soup)       2

[178 rows x 3 columns]

#### Regras de Associação

In [158]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.05)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Waffles),(Fresh Vegetables),0.054623,0.284461,0.013990,0.256120,0.900369,-0.001548,0.961901
1,(Fresh Fruit),(Waffles),0.175286,0.054623,0.010122,0.057748,1.057195,0.000548,1.003316
2,(Waffles),(Fresh Fruit),0.054623,0.175286,0.010122,0.185312,1.057195,0.000548,1.012306
3,(Sliced Bread),(Fresh Vegetables),0.056320,0.284461,0.015241,0.270615,0.951325,-0.000780,0.981017
4,(Fresh Vegetables),(Sliced Bread),0.284461,0.056320,0.015241,0.053579,0.951325,-0.000780,0.997103
...,...,...,...,...,...,...,...,...,...
127,(Wine),(Dried Fruit),0.080677,0.117227,0.010137,0.125646,1.071821,0.000679,1.009629
128,(Wine),(Soup),0.080677,0.120059,0.011273,0.139726,1.163805,0.001587,1.022860
129,(Soup),(Wine),0.120059,0.080677,0.011273,0.093892,1.163805,0.001587,1.014585
130,(Dried Fruit),(Soup),0.117227,0.120059,0.012193,0.104011,0.866329,-0.001881,0.982089
131,(Soup),(Dried Fruit),0.120059,0.117227,0.012193,0.101557,0.866329,-0.001881,0.982559

In [162]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.1)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Sliced Bread),(Fresh Fruit),0.056320,0.175286,0.010942,0.194281,1.108365,0.001070,1.023575
1,(Fresh Fruit),(Sliced Bread),0.175286,0.056320,0.010942,0.062423,1.108365,0.001070,1.006509
2,(Fresh Fruit),(Juice),0.175286,0.053689,0.010769,0.061439,1.144350,0.001358,1.008257
3,(Juice),(Fresh Fruit),0.053689,0.175286,0.010769,0.200589,1.144350,0.001358,1.031652
4,(Fresh Fruit),(Batteries),0.175286,0.053962,0.010798,0.061603,1.141597,0.001339,1.008142

In [163]:
rules[(rules['confidence'] > 0.2) & (rules['lift'] > 1.0)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
3,(Juice),(Fresh Fruit),0.053689,0.175286,0.010769,0.200589,1.144350,0.001358,1.031652
5,(Batteries),(Fresh Fruit),0.053962,0.175286,0.010798,0.200107,1.141597,0.001339,1.031029